name: FTP Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    pull_request:
      - main

jobs:
  web-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Replace password
        run: |
          sed -i "s/PASSWORD_PLACEHOLDER/$PASS/" config.php
          sed -i "s/EMAIL_PLACEHOLDER/$ADDR/" config.php
        env:
          PASS: ${{ secrets.email_password }}
          ADDR: ${{ secrets.email_addr }}

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ftp.ae-isae-supaero.fr
          server-dir: ${{ secrets.deploy_path }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          exclude: .git*
            - .git*/**
            - .github*
            - .github*/**
            - .vscode*
            - .vscode*/**
            - README.md
            - LICENSE
